### ISSUE TITLE
Error during setup 

### ISSUE THREAD

**Issue by Techfazzy** [DZuz14/react-hacker#3]
Hey, I am kind of new to Node.js, home study, I tried to run **"npm-i"** or **"npm start"**, but it all ends in errors something like **index.js.**
This are the screenshots:
![1](https://user-images.githubusercontent.com/59057795/83984027-d5c87600-a900-11ea-9c26-aa35b05fbcf8.png)
![2](https://user-images.githubusercontent.com/59057795/83984028-d6610c80-a900-11ea-98df-1f9843ef4663.png)

###  Please it would be of great help if you assisted****

**Comment by RyanDWilliamson** [comment]
I reinstalled Babel and fixed my issue. 

npm install -D babel-loader @babel/core @babel/preset-env webpack
